
nelmio_cors:
    defaults:
        #allow_credentials: true
        origin_regex: true
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/login':
            #allow_credentials: true
            origin_regex: true
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
        '^/register':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600


# /* // Add headers for CORS
# header('Access-Control-Allow-Origin: http://localhost:8080');
# header('Access-Control-Allow-Credentials: true ');
# header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method");
# header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
# header("Allow: GET, POST, OPTIONS, PUT, DELETE");
# $method = $_SERVER['REQUEST_METHOD'];
# if ($method == "OPTIONS") {
#     die();

